# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run angular test scripts
        run: |
          npm test,
          npm run e2e
      # - name: Angular run unit tests
      #   uses: ahmedrizwan/angular-karma-test-action@v1.0.8
      # - name: Angular run e2e tests
      #   uses: mayur-rawte/github-angular-actions@latest
